### ISSUE TITLE
Failure to build origin-bridge container

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin-box#100]
When using deploy.sh to build and deploy the origin-bridge to production, I run into an apt-get [error](https://gist.github.com/franckc/60d1e61587807208f458cbcfc4ac265c).

I haven't had time to troubleshoot the root cause.

I'm on MacOS 10.136 and Docker 18.06.1-ce-mac73

**Comment by franckc** [comment]
CC @tomlinton

**Comment by tomlinton** [comment]
Normally these kind of errors are when the distribution is out of date and the packages have been removed/renamed from the mirrors. That isn't the case here though as the `python:3.6` tag in the dockerfile means it should be using the latest version of Debian. I don't get this on my machine so it is a bit tricky to diagnose. Some things you could try:

- Appending `--fix-missing` to the `apt-get update -y` command in the dockerfile.
- Removing the `apt-get update -y` command from the dockerfile.

**Comment by franckc** [comment]
Using `apt-get update -y --fix-missing` worked. Will send a PR shortly.
