### ISSUE TITLE
Deploying packages involves sending GBs of data across the network

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin-box#103]
Which is pretty slow/impossible if the pusher is on a slow internet connection.
We should think about setting up a compute box in Google Cloud that pusher can use for doing deployments. Would be much faster.

**Comment by tomlinton** [comment]
I can improve this a lot with the use of smaller containers. In a lot of places I'm using ubuntu/debian based containers, and if I change these to alpine (a stripped down linux distro) there will be a huge reduction in size. I've only stuck with large containers so we have all the debugging utils in the containers that we might need during this initial release.

I think I can probably start testing and moving some over to alpine now.

**Comment by franckc** [comment]
Debugging/troubleshooting tools could be handy though... You don't think we could have a beefy pusher box in Google Cloud that we remotely connect to for doing deployments ?

**Comment by tomlinton** [comment]
Yep I can set that up, it is a much quicker thing to do :grin:. I'd still like to strip down the containers at some point, it'll make improvements for resource usage as well as container size.

**Comment by tomlinton** [comment]
Closing as deployment happens on a remote machine now.
