### ISSUE TITLE
Execution tree on boot up

### ISSUE THREAD

**Issue by ambertch** [OriginProtocol/origin-box#17]
When the box is run, PM2 starts all processes simultaneously (or thereabouts). However, some processes depend on other processes. For instance, the bridge's celery worker process queries the blockchain, which isn't available until origin-js installs its libraries and starts ipfs/ganache.

This could create confusion, as the output logs show errors during this time period.

One solution would be to have some sort of execution tree, whereby processes that depend on other processes do not startup until the dependencies are all running.

**Comment by tyleryasaka** [comment]
Closed by https://github.com/OriginProtocol/origin-box/pull/25
