### ISSUE TITLE
Clarify intended uses

### ISSUE THREAD

**Issue by cuongdo** [OriginProtocol/origin-box#2]
I just finished chatting with @ambertch, and it became clear to us that there are multiple potential uses for this container, such as:

1. Continuous integration testing, using something like Travis CI
2. An easy way for Origin developers, who primarily work on the DApp and Origin.js, to easily get a local bridge server and its dependencies running
3. An easy way for developers to work on any part of the Origin stack

Number 3 seems like less of a priority to me. So, I think we should focus efforts on the first two uses. Any thoughts @tyleryasaka @ambertch?

**Comment by ambertch** [comment]
A solution was found that doesn't appear to suffer any performance issues 🤞 https://github.com/OriginProtocol/origin-box/pull/3

The same or similar setup can be used to do integration testing, which I will work on

**Comment by tyleryasaka** [comment]
I defined my intended use cases in the README: https://github.com/OriginProtocol/origin-box#use-cases.

So, I actually think (3) is more of a priority than (2). The problem with (2) is that we also need a docker container to help people working on the *bridge server*. The bridge server depends on origin-js for a running blockchain. And I think in the long run, there will be a lot of value in being able to get the *entire* stack running with an easy setup for doing development in a real, integrated environment.

As @ambertch pointed out, I the performance issues we were having might have been alleviated by the PR where we're no longer mounting the node_modules folder.

We have a lot of moving parts scattered across repos. It can be really hard to understand how it all works together. The idea of this, in my mind, is to be a place where you can easily run all Origin components together in one environment. To me the use cases are (1) development, (2) testing, and (3) demonstration.
