### ISSUE TITLE
Postgres boots up twice during container build (ubuntu 16.04)

### ISSUE THREAD

**Issue by ambertch** [OriginProtocol/origin-box#28]
termoVrt (in Discord) reported that on ubuntu 16.04, the container build failed with the error:

`sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  the database system is starting up`

On his setup, he traced this to postgres booting up twice here: https://github.com/OriginProtocol/origin-box/blob/master/container/Dockerfile#L70

He reports that with modification, he was able to build the box using docker-compose

**Comment by tomlinton** [comment]
Closed by #29.
