### ISSUE TITLE
Docker-compose not installing package.json dependencies on container rebuild

### ISSUE THREAD

**Issue by tomlinton** [OriginProtocol/origin-box#34]
Under some conditions docker-compose is not installing new dependencies in `package.json` even if a no cache container rebuild is performed with `docker-compose build --no-cache <container name>`. It looks like this is a [known issue](https://github.com/docker/compose/issues/4337).

I'll add documentation to this for the docs, and look at some solutions, but for now a workaround:

**Remove all docker containers and volumes**

This is a complete clean out of all docker containers and volumes. This will also move any non origin-box containers/volumes so be careful

1. `docker-compose down`
2. `docker system prune -a`
3. `docker volume prune`
4. `./install.sh -e origin`

Thanks to @tyleryasaka and @mek32390 for bringing this one to my attention.

**Comment by wanderingstan** [comment]
Added a note on `README.md` about this that we can remove when there is a fix:

https://github.com/OriginProtocol/origin-box/blob/master/README.md#packages-not-found

**Comment by tomlinton** [comment]
Just some extra information:

- This is caused by mounting `node_modules` in a volume.
- When the container is rebuilt a new Docker volume is created and the dependencies get installed into it, but the newly created volume never gets used by other containers.

#36 should mostly solve this. :crossed_fingers: It is a bit of a hack though. If/when this gets resolved in `docker-compose` we can go back to using volumes happily. Probably worth leaving the issue open.

**Comment by tomlinton** [comment]
Update on this for changes in #36.

- This shouldn't happen with `origin-js` anymore because it runs `npm install` every time the container starts.
- This issue no longer happens with `origin-dapp` because it doesn't mount `node_modules` in a volume. You can still get missing module errors but that is because modules are installed during build and not because of this bug. If the modules change you'll need to run `docker-compose build origin-dapp`. It should be very fast because it'll use caching.

See updated readme [here.](https://github.com/OriginProtocol/origin-box#module-not-found-errors)

If this proves too troublesome we can add an `npm install` to the `origin-dapp` container startup and never have to deal with this. It is a tradeoff between slowing down the container startup and having the hassle of manual rebuilding.

Note we don't have a choice with `origin-js` and the `npm install` during startup is necessary because `node_modules` has to live inside a volume so it can also be mounted in the `origin-dapp` container.

 If anyone runs into any issues that this doesn't solve, please ping me on Discord or post here (any error logs would be great).

**Comment by tomlinton** [comment]
Closing this due to lerna and webpack restructure.
