### ISSUE TITLE
Local Messaging Support

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-box#35]
Now that we have [abandoned WebRTC in favor of persistence with IPFS](https://github.com/OriginProtocol/origin-dapp/pull/367/commits/39dd62856759720c48a1859ac12e631c96c3e88e), it isn't easy to develop messaging without storing immutable messages in the "production" OrbitDB. Here are some instructions to reference from The Creator:

⚠️ **Edit**: These instructions are now out of date since switching to js-ipfs.
```
install ipfs using brew
then in your ~/.ipfs/config
add the following line
"Addresses": {
    "Swarm": [
      "/ip4/0.0.0.0/tcp/9012/ws"
    ]
also set your api port to something different than the default
"API": "/ip4/127.0.0.1/tcp/5009",
I used 5009
then in your bridge-server/.env
set the correct variables
ex:
MESSAGING_IPFS_URL=http://127.0.0.1:5009/
MESSAGING_IPFS_AUTH_TOKEN=
MESSAGING_NAMESPACE=
now from the command line you should able to run
ipfs daemon --enable-pubsub-experiment
and then: ipfs id
the result of the ipfs id will give you what the dapp can connect to
then on the bridge you need to do npm run start
easy right?
```

**Comment by tomlinton** [comment]
Sounds like we need a new container for the stack? :sunglasses: I can add one on and integrate it.

**Comment by micahalcorn** [comment]
You're my hero, @tomlinton 🏆 Can this run in the "standard stack" alongside the other bridge container?

**Comment by micahalcorn** [comment]
Sorry, we've now switched from go-ipfs to js-ipfs. So that should simplify the work needed here, but I suppose that it should still be another container.

**Comment by tomlinton** [comment]
Not a problem. It seems like this IPFS stuff almost belongs in a separate repo now that both `origin-js` and `origin-bridge` are firing up IPFS services. Or are you trying to bully the last of the Python out of origin? :joy: We probably don't want to add more repos but maybe if/when we move to a monorepo we could move all the IPFS stuff into a subdirectory outside of each of the projects.

**Comment by micahalcorn** [comment]
Yes to all of that ✅

**Comment by tomlinton** [comment]
What is necessary to configure `origin-dapp` to use the orbit db server? I checked back through the commit history and it looks like IPFS_SWARM might be the relevant config setting. It never made it to the dev.env file though, is that what I am after?

**Comment by micahalcorn** [comment]
Yes, `IPFS_SWARM=/ip4/127.0.0.1/tcp/9012/ws/ipfs/{SOME_ID_HERE}` ✔️

**Comment by micahalcorn** [comment]
@tomlinton I'm realizing that I probably haven't documented this anywhere yet, as it just came together late last week:

_origin-dapp_
- `IPFS_SWARM` needs to match the peer address that is produced by running `npm start` in origin-bridge
- `MESSAGING_NAMESPACE` should default to `dev` but can be anything
- `MESSAGING_ACCOUNT` should be an Ethereum address, but probably default to `undefined`

_origin-bridge_
- `MESSAGING_IPFS_WS_ADDRESS` should be `/ip4/0.0.0.0/tcp/9012/ws`
- `MESSAGING_NAMESPACE` can be anything but needs to match the same in origin-dapp

**Comment by micahalcorn** [comment]
Magically handled by #39 🎉
