### ISSUE TITLE
Install script should detect git clone failures

### ISSUE THREAD

**Issue by tomlinton** [OriginProtocol/origin-box#40]
Since we changed the git clone commands to use SSH by default (#32) in the install script I've had a few reports of failures due to people not having SSH keys configured on GitHub. The install script should handle SSH failures and revert to https when cloning the repositories.

**Comment by sparrowDom** [comment]
If the fallback does not work we could exit the script with the error message on how to setup the ssh connectivity. Maybe something like: "Can not ssh to Github. Make sure you have your public keys configured in Github Account Settings."

It really depends on how technically proficient we expect users that install origin will be. If broader set of people should be able to do this, we should probably make error messages extra explanatory with links to solutions.

**Comment by cuongdo** [comment]
Might it make sense to switch the default back to https to make things easy for users who are less knowledgeable about SSH? 

Users who know SSH always have the option of switching their remote to SSH, which is [well documented on GitHub](https://help.github.com/articles/changing-a-remote-s-url/). We could even have a simple bash script to automate this.

**Comment by tomlinton** [comment]
Closing as there is no longer a `git clone` step.
