### ISSUE TITLE
Install script ssh github connectivity check

### ISSUE THREAD

**Issue by sparrowDom** [OriginProtocol/origin-box#46]
If user does not have public key configured with his Github accounts `install.sh` script will not fail trying to checkout repositories. It would be nice if it would fail with an error message. Maybe something similar to: "Can not ssh to Github. Make sure you have your public keys configured in Github Account Settings."

**Comment by micahalcorn** [comment]
Related: https://github.com/OriginProtocol/origin-box/issues/40

**Comment by sparrowDom** [comment]
Hmm actually this is a duplicate of #40 Closing the bug
