### ISSUE TITLE
deploy.sh does not deploy package if githash identical

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin-box#78]
Shows "Deployed container tag is the same as new deploy tag, appending unix timestamp to tag to force Kubernetes to update deployment" during build, creates correctly new build with timestamp and uploads to gcr.io, but the image tag in kubernetes/values/values-<env>.yaml does not get updated and therefore Helm does not deploy new container.

**Comment by tomlinton** [comment]
Thanks @franckc! PR is up.

**Comment by franckc** [comment]
Thank you for the quick fix !
