### ISSUE TITLE
Running python tests from docker

### ISSUE THREAD

**Issue by sparrowDom** [OriginProtocol/origin-box#8]
Not sure if this repository is the right location or should I post this to [bridge-server](https://github.com/OriginProtocol/bridge-server) repository. 

When connecting to docker with [scripts/cli.sh](https://github.com/OriginProtocol/origin-box/blob/master/scripts/cli.sh) user is signed in as root user. And when I try to run `pytest` I get the following error: 
```
RuntimeError: initdb failed: b'initdb: cannot be run as root\nPlease log in (using, e.g., "su") as the (unprivileged) user that will\nown the server process.\n'
```

So I've written a small script `run-test.sh` and put it into `/opt/bridge-server/scripts` that sources the right environment, checks for pip install and runs server tests as `postgres` user. 

Didn't want to make a Pull Request, because I am not sure this is the correct approach to solve this problem. 

`run-test.sh`
```
#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

pip install -r $DIR/../source/requirements.txt -q
su -c "source $DIR/../bridge-server-venv/bin/activate && cd $DIR/../source && pytest $*" postgres
```

any thoughts on this?

**Comment by tyleryasaka** [comment]
@sparrowDom Feel free to open a pull request! Definitely should be an issue on this repo (not bridge-server).

I'm wondering why `pytest` doesn't just work the way it's supposed to (after activating the environment)?

**Comment by sparrowDom** [comment]
@tyleryasaka when I try to run `pytest` after source-ing the environment all the tests fail with the following message: 
```
RuntimeError: initdb failed: b'initdb: cannot be run as root\nPlease log in (using, e.g., "su") as the (unprivileged) user that will\nown the server process.\n'
```

Seems that it is forbidden to run initdb command as a root user, that is why that little script runs source environment and `pytest` as `postgres` user. 

Will make a PR

**Comment by tyleryasaka** [comment]
Completed by #13
